<div class="foot">
    <div class="info-foot">
        <div class="container">
            <div class="row">
                <div class="col-sm ft-list">
                    <ul> <i class="fas fa-bars"></i> Plan de site
                        <li><a class="ft-lnk" href="./"><i class="fas fa-home"></i> Accueil</a></li>
                        <li><a class="ft-lnk" href="#"><i class="fas fa-bread-slice"></i> Notre menu</a></li>
                        <li><a class="ft-lnk" href="./contact.php"><i class="fab fa-facebook-messenger"></i> Contactez-nous</a></li>
                        <li><a class="ft-lnk" href="./apropos.php"><i class="fas fa-address-card"></i> A propos nous</a></li>
                    </ul>
                </div>
                <div class="col-sm ft-list">
                    <ul><i class="fab fa-facebook-messenger"></i> Contactez-nous</a>
                        <li><a class="ft-lnk"><i class="fas fa-map-marker-alt"></i> 2036 LA SOUKRA, ARIANA, Tunisie</a></li>
                        <li><a class="ft-lnk"><i class="fas fa-envelope"></i> boulangerie100@exemple.co</a></li>
                        <li><a class="ft-lnk"><i class="fas fa-phone"></i> +216 15 789 428</a></li>
                    </ul>
                </div>
                <div class="col-sm ft-list">
                    <ul><i class="fas fa-share-alt"></i> Réseaux sociaux
                        <li><a class="ft-lnk"><i class="fab fa-facebook-square"></i> Bakery in FB</a></li>
                        <li><a class="ft-lnk"><i class="fab fa-vk"></i> Bakery in VK</a></li>
                        <li><a class="ft-lnk"><i class="fab fa-twitter"></i> Bakery in TW</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="foot-bar">
        <p>Building By <a href="/" class="text-success text-decoration-none">Mkaddem Oussama</a> &copy;</p>
    </div>
</div>