<a href="/" id="back">Back <i class="fas fa-hand-point-left"></i></a>
<div class="top">
    <div class="info-top">
        <div class="mail">
            <i class="fas fa-envelope"></i> boulangerie100@exemple.co
        </div>
        <div class="tel">
            <i class="fas fa-phone"></i> +216 15 789 428
        </div>
    </div>
    <div class="top-bar">
        <div class="left">
            <a href="./"><img src="./images/logo.png" alt="logo"></a>
            <button id="btn-lnk" class="no-act"><i class="fas fa-bars"></i></button>
        </div>
        <div class="right">
            <ul id="list">
                <li><a class="lnk" id="home" href="./"><i class="fas fa-home"></i> Accueil</a></li>
                <li><a class="lnk" id="prod" href="#"><i class="fas fa-bread-slice"></i> Notre menu</a></li>
                <li><a class="lnk" id="contact" href="./contact.php"><i class="fab fa-facebook-messenger"></i> Contactez-nous</a></li>
                <li><a class="lnk" id="about" href="./apropos.php"><i class="fas fa-address-card"></i> A propos nous</a></li>
            </ul>
        </div>
    </div>
</div>